version: '2' # specify docker-compose version

# Define the services/containers to be run
services:

  angular: # name of the first service
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forewarding
    volumes:
     - ./angular-client:/app # creates a volume so that the image doesn't have to be rebuilt every time  a change is made
     - /app/node_modules

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
    - database # link this service to the database service
    volumes:
     - ./express-server:/usr/src/app/express # creates a volume so that the image doesn't have to be rebuilt every time  a change is made
     - ../storage/public:/usr/src/app/express/public

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27018:27017" # specify port forewarding
    volumes:
      - ../storage/mongohost:/data/db

## Replaces data with what is in the dump folder in storage
##  mongo-seed:
##    image: mongo
##    links:
##      - database
##    volumes:
##      - ../storage/dump:/seed-data
##    command:
##      'bash -c "mongorestore --host database ./seed-data"'
